spring.datasource.url=jdbc:h2:mem:codewordledb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.sql.init.mode=always
spring.datasource.initialization-mode=always
spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp
# logging de jdbc si lo quieres
logging.level.org.springframework.jdbc.core=DEBUG
spring.mvc.view.encoding=UTF-8
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
